# GitHub Actions workflow to run unit tests using make test
name: Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Install make
        run: sudo apt-get update && sudo apt-get install -y make

      - name: Run unit tests
        run: make test
